import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

// IMPORT COMPONENTS
import Chat from '../components/Chat';

export default function Home({ user, auth, db, chatsSnapshot, userIdSnapshot }) {
  const [isOpen, setIsOpen] = useState(false);
  const [chatId, setChatId] = useState("");
  const [users, setUsers] = useState([]);

  // Fill an array of users, enrolled in current chat
  const fillUsersInChat = (chatsSnapshot) => {
    chatsSnapshot?.docs?.map((chat) => (
      setUsers(chat.data().users)
    ));
  };

  const handleClick = () => {
    setIsOpen(!isOpen)
    fillUsersInChat(chatsSnapshot);
    setChatId(chatsSnapshot.docs[0].id);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handleClick}>Messagerie</button>
      {isOpen && (
        <Chat user={user} auth={auth} db={db} users={users} chatId={chatId} />
      )}
    </div>
  )
}
